### ISSUE TITLE
希望加一个顶部/底部弹幕是否显示的开关

### ISSUE THREAD

**Issue by bakasine** [MUTED64/SakuraDanmaku#3]
最近食用的时候发现看很多动漫的时候 有一堆底部弹幕会挡住字幕  希望能加上一个和b站类似的隐藏底部弹幕的开关

**Comment by MUTED64** [comment]
最近比较忙，有空了会看看加个开关

**Comment by MUTED64** [comment]
已经在 commit 3dfffb5 中添加。
